name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - run: |
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install gfortran && sudo apt-get install gfortran-10
          cd source
          mkdir build
          mkdir lib
          make
          make build
          make install
